from pathlib import Path

from typer.testing import CliRunner

from k8s_forge.cli import app

runner = CliRunner()


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def valid_app_yaml(name: str = "demo-app") -> str:
    return f"""app:
  name: {name}
  namespace: {name}
  image: ghcr.io/example/{name}:0.1.0
  containerPort: 8000
  replicas: 1

config:
  enabled: true
  data:
    APP_MODE: "review-required"

service:
  enabled: true
  port: 80
"""


def test_cli_explain_help() -> None:
    result = runner.invoke(app, ["explain", "--help"])

    assert result.exit_code == 0
    output = result.output.lower()
    assert "path to app.yaml" in output
    assert "explain" in output


def test_cli_explain_errors_for_missing_file(tmp_path: Path) -> None:
    result = runner.invoke(app, ["explain", str(tmp_path / "missing.yaml")])

    assert result.exit_code == 1
    assert "Unable to read configuration file" in result.output


def test_cli_explain_errors_for_invalid_yaml(tmp_path: Path) -> None:
    config_path = tmp_path / "invalid.yaml"
    write(config_path, "app: [")

    result = runner.invoke(app, ["explain", str(config_path)])

    assert result.exit_code == 1
    assert "Invalid YAML configuration file" in result.output


def test_cli_explain_valid_minimal_file(tmp_path: Path) -> None:
    config_path = tmp_path / "app.yaml"
    write(config_path, valid_app_yaml())

    result = runner.invoke(app, ["explain", str(config_path)])

    assert result.exit_code == 0
    assert "Application" in result.output
    assert "- name: demo-app" in result.output
    assert "Readiness meaning" in result.output
    assert "Warnings" in result.output
    assert "image placeholder detected" in result.output
    assert "config values require review" in result.output


def test_cli_explain_discovery_generated_file(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    write(repo / "requirements.txt", "fastapi\nuvicorn\n")
    write(repo / "main.py", "from fastapi import FastAPI\napp = FastAPI()\n")
    output_dir = tmp_path / "generated-discovery"
    discover = runner.invoke(
        app,
        ["discover", str(repo), "--output", str(output_dir), "--force"],
    )
    assert discover.exit_code == 0

    generated_yaml = output_dir / "k8s-forge-app.yaml"
    result = runner.invoke(app, ["explain", str(generated_yaml)])

    assert result.exit_code == 0
    assert "config potentially generated by discovery" in result.output
    assert "starter configuration" in result.output


def test_cli_explain_has_no_side_effect_on_input_file(tmp_path: Path) -> None:
    config_path = tmp_path / "app.yaml"
    content = valid_app_yaml("readonly-app")
    write(config_path, content)

    result = runner.invoke(app, ["explain", str(config_path)])

    assert result.exit_code == 0
    assert config_path.read_text(encoding="utf-8") == content
