from k8s_forge.explain import build_explanation
from k8s_forge.explain_renderer import render_explanation
from k8s_forge.models import AppConfig


def minimal_config() -> AppConfig:
    return AppConfig.model_validate(
        {
            "app": {
                "name": "demo-app",
                "namespace": "demo-app",
                "image": "ghcr.io/example/demo-app:0.1.0",
                "containerPort": 8000,
                "replicas": 1,
            },
            "config": {
                "enabled": True,
                "data": {
                    "DISCOVERY_REVIEW": "required",
                    "APP_MODE": "review-required",
                },
            },
            "service": {"enabled": True, "port": 80},
        }
    )


def test_build_explanation_contains_application_summary() -> None:
    report = build_explanation(minimal_config())
    text = render_explanation(report)

    assert "Application" in text
    assert "- name: demo-app" in text
    assert "- namespace: demo-app" in text
    assert "- image: ghcr.io/example/demo-app:0.1.0" in text
    assert "- container port: 8000" in text


def test_build_explanation_detects_pedagogical_warnings() -> None:
    report = build_explanation(minimal_config())

    assert "image placeholder detected" in report.warnings
    assert "config values require review" in report.warnings
    assert "config potentially generated by discovery" in report.warnings
    assert "ingress disabled" in report.warnings
    assert "probes missing" in report.warnings
    assert "secrets disabled" in report.warnings
    assert "networkPolicy disabled" in report.warnings
    assert "autoscaling disabled" in report.warnings
    assert "security module disabled" in report.warnings
    assert "capstone module disabled" in report.warnings


def test_build_explanation_detects_low_educational_resources() -> None:
    config = AppConfig.model_validate(
        {
            "app": {
                "name": "api",
                "namespace": "api",
                "image": "ghcr.io/acme/api:1.0.0",
                "containerPort": 8080,
                "replicas": 1,
            },
            "resources": {
                "requests": {"cpu": "50m", "memory": "64Mi"},
                "limits": {"cpu": "250m", "memory": "128Mi"},
            },
        }
    )

    report = build_explanation(config)

    assert "resources are low educational defaults" in report.warnings


def test_build_explanation_reports_enabled_modules() -> None:
    config = AppConfig.model_validate(
        {
            "app": {
                "name": "api",
                "namespace": "api",
                "image": "ghcr.io/acme/api:1.0.0",
                "containerPort": 8080,
                "replicas": 2,
            },
            "service": {"enabled": True, "port": 80},
            "networkPolicy": {"enabled": True},
            "security": {"enabled": True},
            "capstone": {"enabled": True},
        }
    )

    text = render_explanation(build_explanation(config))

    assert "NetworkPolicy" in text
    assert "- status: enabled" in text
    assert "Security" in text
    assert "Capstone" in text


def test_build_explanation_describes_job_workload() -> None:
    config = AppConfig.model_validate(
        {
            "app": {
                "name": "network-mapper",
                "namespace": "network-mapper",
                "image": "network-mapper:dev",
            },
            "workload": {
                "type": "job",
                "command": ["python"],
                "args": ["-m", "network_mapper"],
                "restartPolicy": "OnFailure",
            },
            "service": {"enabled": False, "port": 80},
        }
    )

    text = render_explanation(build_explanation(config))

    assert "Workload" in text
    assert "- type: job" in text
    assert "- rendered as: batch/v1 Job" in text
    assert "- port not applicable for workload type job" in text
    assert "- applicable: no" in text
    assert "target port: not applicable for workload type job" in text


def test_build_explanation_warns_job_without_command() -> None:
    config = AppConfig.model_validate(
        {
            "app": {
                "name": "network-mapper",
                "namespace": "network-mapper",
                "image": "network-mapper:dev",
            },
            "workload": {"type": "job", "restartPolicy": "OnFailure"},
            "service": {"enabled": False, "port": 80},
        }
    )

    report = build_explanation(config)

    assert "job workload has no explicit command" in report.warnings


def test_build_explanation_describes_cronjob_workload() -> None:
    config = AppConfig.model_validate(
        {
            "app": {
                "name": "network-mapper",
                "namespace": "network-mapper",
                "image": "network-mapper:dev",
            },
            "workload": {
                "type": "cronjob",
                "command": ["python"],
                "args": ["-m", "network_mapper"],
                "restartPolicy": "OnFailure",
                "schedule": "0 * * * *",
            },
            "service": {"enabled": False, "port": 80},
        }
    )

    text = render_explanation(build_explanation(config))

    assert "- type: cronjob" in text
    assert "- schedule: 0 * * * *" in text
    assert "- rendered as: batch/v1 CronJob" in text


def test_build_explanation_marks_worker_port_not_applicable() -> None:
    config = AppConfig.model_validate(
        {
            "app": {
                "name": "demo-worker",
                "namespace": "demo-worker",
                "image": "demo-worker:dev",
            },
            "workload": {
                "type": "worker",
                "command": ["python"],
                "args": ["-m", "worker"],
            },
            "service": {"enabled": False, "port": 80},
        }
    )

    text = render_explanation(build_explanation(config))

    assert "- port not applicable for workload type worker" in text
    assert "target port: not applicable for workload type worker" in text


def test_build_explanation_marks_cronjob_port_not_applicable() -> None:
    config = AppConfig.model_validate(
        {
            "app": {
                "name": "network-mapper",
                "namespace": "network-mapper",
                "image": "network-mapper:dev",
            },
            "workload": {
                "type": "cronjob",
                "command": ["python"],
                "args": ["-m", "network_mapper"],
                "restartPolicy": "OnFailure",
                "schedule": "0 * * * *",
            },
            "service": {"enabled": False, "port": 80},
        }
    )

    text = render_explanation(build_explanation(config))

    assert "- port not applicable for workload type cronjob" in text
    assert "target port: not applicable for workload type cronjob" in text
