"""Assisted Studio scaffold helpers."""

from __future__ import annotations

import shlex
from dataclasses import dataclass
from typing import Literal

import yaml

WorkloadType = Literal["deployment", "worker", "job", "cronjob"]
RestartPolicy = Literal["Always", "Never", "OnFailure"]


@dataclass(frozen=True)
class AssistedScaffoldRequest:
    """User-reviewed scaffold values from Studio."""

    app_name: str
    namespace: str
    image: str
    workload_type: WorkloadType
    startup_command: str
    container_port: int | None = None
    service_enabled: bool = False
    restart_policy: RestartPolicy = "Always"
    schedule: str = ""
    persistence_required: bool = False


class ScaffoldValidationError(ValueError):
    """Raised when assisted scaffold input is incomplete or unsafe."""


def build_assisted_app_yaml(request: AssistedScaffoldRequest) -> str:
    """Build a validated starter app.yaml from explicit user input."""
    _validate_request(request)
    command, args = _split_command(request.startup_command)
    container_port = request.container_port or 8000
    service_enabled = request.service_enabled and request.workload_type == "deployment"
    data: dict[str, object] = {
        "app": {
            "name": request.app_name,
            "namespace": request.namespace,
            "image": request.image,
            "containerPort": container_port,
            "replicas": 1,
        },
        "workload": {
            "type": request.workload_type,
            "command": command,
            "args": args,
            "restartPolicy": request.restart_policy,
            "schedule": request.schedule,
        },
        "config": {
            "enabled": True,
            "data": {
                "ASSISTED_SCAFFOLD": "review-required",
                "PERSISTENCE_REQUIRED": (
                    "review-required" if request.persistence_required else "false"
                ),
            },
        },
        "secrets": {},
        "service": {"enabled": service_enabled, "port": 80},
        "resources": {
            "requests": {"cpu": "50m", "memory": "64Mi"},
            "limits": {"cpu": "250m", "memory": "128Mi"},
        },
        "probes": {"liveness": None, "readiness": None},
        "autoscaling": {"enabled": False},
        "ingress": {"enabled": False},
        "networkPolicy": {"enabled": False},
        "policy": {"enabled": False},
        "supplyChain": {"enabled": False},
        "ci": {"enabled": False},
        "gitops": {"enabled": False},
        "observability": {"enabled": False},
        "logging": {"enabled": False},
        "tracing": {"enabled": False},
        "terraform": {"enabled": False},
        "ansible": {"enabled": False},
        "security": {"enabled": False},
        "capstone": {"enabled": False},
    }
    return (
        "# Generated by k8s-forge Studio assisted scaffold.\n"
        "# Review required. This file is not deployment-ready by default.\n"
        + yaml.safe_dump(data, sort_keys=False)
    )


def build_dockerfile_proposal(workload_type: WorkloadType, web: bool = False) -> str:
    """Return a Dockerfile proposal without writing it to the repository."""
    if web or workload_type == "deployment":
        return """FROM python:3.12-slim

RUN groupadd --gid 10001 app \
    && useradd --uid 10001 --gid 10001 --create-home --shell /usr/sbin/nologin app

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=10001:10001 . .

EXPOSE 8000

USER 10001:10001

CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
    return """FROM python:3.12-slim

RUN groupadd --gid 10001 app \
    && useradd --uid 10001 --gid 10001 --create-home --shell /usr/sbin/nologin app

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=10001:10001 . .

USER 10001:10001

CMD ["python", "-m", "MODULE_NAME"]
"""


def _validate_request(request: AssistedScaffoldRequest) -> None:
    if not request.app_name.strip():
        raise ScaffoldValidationError("Application name is required.")
    if not request.namespace.strip():
        raise ScaffoldValidationError("Namespace is required.")
    if not request.image.strip():
        raise ScaffoldValidationError("Image is required.")
    if not request.startup_command.strip():
        raise ScaffoldValidationError("Startup command is required.")
    if request.workload_type == "deployment":
        if request.container_port is None:
            raise ScaffoldValidationError(
                "Web service scaffold requires a container port."
            )
        if not request.service_enabled:
            raise ScaffoldValidationError(
                "Web service scaffold requires Service enabled."
            )
    if request.workload_type in {"worker", "job"} and request.service_enabled:
        raise ScaffoldValidationError(
            f"{request.workload_type} scaffold requires Service disabled."
        )
    if request.workload_type == "job" and request.restart_policy == "Always":
        raise ScaffoldValidationError(
            "Job scaffold requires restartPolicy Never or OnFailure."
        )
    if request.workload_type == "cronjob":
        if request.service_enabled:
            raise ScaffoldValidationError("CronJob scaffold requires Service disabled.")
        if request.restart_policy == "Always":
            raise ScaffoldValidationError(
                "CronJob scaffold requires restartPolicy Never or OnFailure."
            )
        if not request.schedule.strip():
            raise ScaffoldValidationError("CronJob scaffold requires a schedule.")


def _split_command(command: str) -> tuple[list[str], list[str]]:
    try:
        parts = shlex.split(command)
    except ValueError as exc:
        raise ScaffoldValidationError("Startup command could not be parsed.") from exc
    if not parts:
        raise ScaffoldValidationError("Startup command is required.")
    return [parts[0]], parts[1:]
