"""Pedagogical explanation helpers for app.yaml configuration files."""

from __future__ import annotations

from dataclasses import dataclass, field

from k8s_forge.models import AppConfig


@dataclass(frozen=True)
class ExplanationSection:
    """A titled explanation section."""

    title: str
    items: list[str]


@dataclass(frozen=True)
class ExplanationReport:
    """Structured explanation of a validated app.yaml configuration."""

    sections: list[ExplanationSection]
    warnings: list[str] = field(default_factory=list)
    next_steps: list[str] = field(default_factory=list)


def _state(enabled: bool) -> str:
    return "enabled" if enabled else "disabled"


def _has_resources(config: AppConfig) -> bool:
    requests = config.resources.requests
    limits = config.resources.limits
    return all((requests.cpu, requests.memory, limits.cpu, limits.memory))


def _parse_cpu_millicores(value: str | None) -> int | None:
    if not value:
        return None
    if value.endswith("m") and value[:-1].isdigit():
        return int(value[:-1])
    if value.isdigit():
        return int(value) * 1000
    return None


def _parse_memory_mib(value: str | None) -> int | None:
    if not value:
        return None
    lower = value.lower()
    if lower.endswith("mi") and lower[:-2].isdigit():
        return int(lower[:-2])
    if lower.endswith("gi") and lower[:-2].isdigit():
        return int(lower[:-2]) * 1024
    return None


def _resources_are_weak(config: AppConfig) -> bool:
    requests = config.resources.requests
    limits = config.resources.limits
    request_cpu = _parse_cpu_millicores(requests.cpu)
    limit_cpu = _parse_cpu_millicores(limits.cpu)
    request_memory = _parse_memory_mib(requests.memory)
    limit_memory = _parse_memory_mib(limits.memory)
    return any(
        (
            request_cpu is not None and request_cpu <= 50,
            limit_cpu is not None and limit_cpu <= 250,
            request_memory is not None and request_memory <= 64,
            limit_memory is not None and limit_memory <= 128,
        )
    )


def _resources_summary(config: AppConfig) -> list[str]:
    requests = config.resources.requests
    limits = config.resources.limits
    return [
        f"requests.cpu: {requests.cpu or 'not set'}",
        f"requests.memory: {requests.memory or 'not set'}",
        f"limits.cpu: {limits.cpu or 'not set'}",
        f"limits.memory: {limits.memory or 'not set'}",
    ]


def _probes_summary(config: AppConfig) -> list[str]:
    return [
        f"liveness: {config.probes.liveness or 'not set'}",
        f"readiness: {config.probes.readiness or 'not set'}",
    ]


def _config_items(config: AppConfig) -> list[str]:
    if not config.config:
        return ["status: disabled or empty"]
    return [f"{key}: {value}" for key, value in sorted(config.config.items())]


def _secret_items(config: AppConfig) -> list[str]:
    if not config.secrets:
        return ["status: disabled or empty"]
    return [
        f"{key}: configured placeholder/review value" for key in sorted(config.secrets)
    ]


def _config_requires_review(config: AppConfig) -> bool:
    for key, value in config.config.items():
        if key == "DISCOVERY_REVIEW":
            return True
        if value.strip().lower() == "review-required":
            return True
    return False


def _image_is_placeholder(image: str) -> bool:
    return image.startswith("ghcr.io/example/")


def _warnings(config: AppConfig) -> list[str]:
    warnings: list[str] = []
    if _image_is_placeholder(config.app.image):
        warnings.append("image placeholder detected")
    if _config_requires_review(config):
        warnings.append("config values require review")
        warnings.append("config potentially generated by discovery")
    if not config.ingress.enabled:
        warnings.append("ingress disabled")
    if not config.probes.liveness or not config.probes.readiness:
        warnings.append("probes missing")
    if not config.secrets:
        warnings.append("secrets disabled")
    if not _has_resources(config):
        warnings.append("resources missing")
    elif _resources_are_weak(config):
        warnings.append("resources are low educational defaults")
    if not config.networkPolicy.enabled:
        warnings.append("networkPolicy disabled")
    if not config.autoscaling.enabled:
        warnings.append("autoscaling disabled")
    if not config.security.enabled:
        warnings.append("security module disabled")
    if not config.capstone.enabled:
        warnings.append("capstone module disabled")
    return warnings


def build_explanation(config: AppConfig) -> ExplanationReport:
    """Build a read-only educational explanation for a validated configuration."""
    sections = [
        ExplanationSection(
            "Application",
            [
                f"name: {config.app.name}",
                f"namespace: {config.app.namespace}",
                f"image: {config.app.image}",
                f"container port: {config.app.containerPort}",
                f"replicas: {config.app.replicas}",
            ],
        ),
        ExplanationSection(
            "Readiness meaning",
            [
                "This file is a starter configuration.",
                "It is not deployment-ready by default.",
                "Review required values before rendering or deploying "
                "anything manually.",
            ],
        ),
        ExplanationSection("Image", [f"image: {config.app.image}"]),
        ExplanationSection("Namespace", [f"namespace: {config.app.namespace}"]),
        ExplanationSection("Port", [f"containerPort: {config.app.containerPort}"]),
        ExplanationSection(
            "Service",
            [
                f"status: {_state(config.service.enabled)}",
                f"service port: {config.service.port}",
                f"target port: {config.app.containerPort}",
            ],
        ),
        ExplanationSection(
            "Ingress",
            [
                f"status: {_state(config.ingress.enabled)}",
                f"host: {config.ingress.host or 'not set'}",
                f"TLS: {_state(config.ingress.tls.enabled)}",
                f"cert-manager: {_state(config.ingress.certManager.enabled)}",
            ],
        ),
        ExplanationSection("Config", _config_items(config)),
        ExplanationSection("Secrets", _secret_items(config)),
        ExplanationSection("Resources", _resources_summary(config)),
        ExplanationSection("Probes", _probes_summary(config)),
        ExplanationSection(
            "Autoscaling",
            [
                f"status: {_state(config.autoscaling.enabled)}",
                f"min replicas: {config.autoscaling.minReplicas}",
                f"max replicas: {config.autoscaling.maxReplicas}",
                f"CPU target: {config.autoscaling.targetCPUUtilizationPercentage}%",
            ],
        ),
        ExplanationSection(
            "NetworkPolicy",
            [
                f"status: {_state(config.networkPolicy.enabled)}",
                f"profile: {config.networkPolicy.profile}",
            ],
        ),
        ExplanationSection(
            "Policy / Kyverno",
            [
                f"status: {_state(config.policy.enabled)}",
                f"provider: {config.policy.provider}",
                f"mode: {config.policy.validationFailureAction}",
            ],
        ),
        ExplanationSection(
            "Supply Chain",
            [
                f"status: {_state(config.supplyChain.enabled)}",
                f"scan: {_state(config.supplyChain.scan.enabled)}",
                f"SBOM: {_state(config.supplyChain.sbom.enabled)}",
                f"signing: {_state(config.supplyChain.signing.enabled)}",
            ],
        ),
        ExplanationSection(
            "CI",
            [
                f"status: {_state(config.ci.enabled)}",
                f"provider: {config.ci.provider}",
            ],
        ),
        ExplanationSection(
            "GitOps",
            [
                f"status: {_state(config.gitops.enabled)}",
                f"provider: {config.gitops.provider}",
            ],
        ),
        ExplanationSection(
            "Observability",
            [
                f"status: {_state(config.observability.enabled)}",
                f"provider: {config.observability.provider}",
            ],
        ),
        ExplanationSection(
            "Logging",
            [
                f"status: {_state(config.logging.enabled)}",
                f"provider: {config.logging.provider}",
            ],
        ),
        ExplanationSection(
            "Tracing",
            [
                f"status: {_state(config.tracing.enabled)}",
                f"provider: {config.tracing.provider}",
                f"backend: {config.tracing.backend.type}",
            ],
        ),
        ExplanationSection(
            "Terraform",
            [
                f"status: {_state(config.terraform.enabled)}",
                f"backend: {config.terraform.backend.type}",
            ],
        ),
        ExplanationSection(
            "Ansible",
            [
                f"status: {_state(config.ansible.enabled)}",
                f"inventory: {config.ansible.inventory.type}",
            ],
        ),
        ExplanationSection(
            "Security",
            [
                f"status: {_state(config.security.enabled)}",
                f"container review: {_state(config.security.container.enabled)}",
                f"checklist: {_state(config.security.checklist.enabled)}",
            ],
        ),
        ExplanationSection(
            "Capstone",
            [
                f"status: {_state(config.capstone.enabled)}",
                f"modules summary: {_state(config.capstone.modules_summary.enabled)}",
                f"v1 readiness: {_state(config.capstone.v1_readiness.enabled)}",
            ],
        ),
    ]
    return ExplanationReport(
        sections=sections,
        warnings=_warnings(config),
        next_steps=[
            "Replace placeholder image values with a real reviewed image.",
            "Review config and secret handling before rendering manifests.",
            "Run k8s-forge check before any render workflow.",
            "Enable security and capstone readiness when preparing final "
            "review material.",
        ],
    )
